website/music/urls.py
from django.conf.urls import url
from . import views # importing the created functions

# creating a namespace, this creates specificity if we have several urls under the same names
app_name = 'music'

urlpatterns = [
    # /music/ - This url pattern will be under the name "IndexView"
    url(r'^$', views.IndexView.as_view(), name='index'), 

    url(r'^register/$', views.UserFormView.as_view(), name='register'),
    
    # /music/<pk>/ - the number in the url will be saved as <pk> and we'll pass it to the DetailsView class in views
    url(r'^(?P<pk>[0-9]+)/$', views.DetailsView.as_view(), name='detail'), # detail will be the name of this url pattern

    # /music/album/add/  this url is for when we want to create a new album
    url(r'album/add/$', views.AlbumCreate.as_view(), name='album-add'),

    # /music/album/2/  this url is for when we want to update an album with a primary key of <pk>
    url(r'album/(?P<pk>[0-9]+)/$', views.AlbumUpdate.as_view(), name='album-update'),

    # /music/album/2/delete/
    url(r'album/(?P<pk>[0-9]+)/delete/$', views.AlbumDelete.as_view(), name='album-delete'),

]

website/website/urls.py
# Website urls
from django.contrib import admin
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # namespace is for situations when more than one app contains views with the same name. Specificity
    url(r'^music/', include('music.urls', namespace='music')), # when music page is requested, head over to the music app's url file to handle the request
]
# whenever we're in developer mode, use the media directory we specified in settings
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

website/music/models.py
from django.db import models
from django.urls import reverse
# ONly do migrations if you add or delete columns/attributes to the database
# python manage.py makemigrations music
# then - python manage.py migrate

# Create table for database, each variable represents a column
# these tables will automatically make a unique primary key named 'id' for each 'album' made
class Album(models.Model):
    artist = models.CharField(max_length=50)
    album_title = models.CharField(max_length=100)
    genre = models.CharField(max_length=50)
    album_logo = models.FileField() # Allow the user to upload an image file
    # whenever a new album is made, return the details page of the new album that was made
    def get_absolute_url(self):
        return reverse("music:detail", kwargs={"pk": self.pk})
    

    # this is a special method that gives a string representation of the object
    def __str__(self):
        # we now specify what that string will be
        return self.album_title + ' - ' + self.artist

class Song(models.Model):
    # we need to associate the songs with an album, so make a foreign key
    # models.cascade...once we delete an album that contains the song, delete the song as well
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=100)
    is_favorite = models.BooleanField(default=False)

    #lets make a string representation of a song
    def __str__(self):
        return self.song_title

website/music/forms.py
from django.contrib.auth.models import User
from django import forms

# inherit from base form class and override it and make our own 
class UserForm(forms.ModelForm):
    # we want the password characters to be hidden
    password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        # specify the db we will be using
        model = User
        # what fields do we want to appear in the form?
        fields = ['username', 'email', 'password']

website/music/views.py
from django.views import generic
from .models import Album
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, DeleteView 
from django.views.generic import View
from .forms import UserForm

class IndexView(generic.ListView): # used ListView because the index page will be a list of all the albums
    # specify the template that will be used
    template_name = 'music/index.html'
    # query the database for the data that you want, and then return it to the template for user viewing
    context_object_name = 'all_albums'

    def get_queryset(self):
        # return "object_list" object_list is the default variable name
        return Album.objects.all() # we want all of the albums for the index page in a list of objects.

class DetailsView(generic.DetailView):# used detail view because this page is for details about a specific album
    # specify the model you want the details of
    model = Album
    # specify the template you want to plug the model into
    template_name = 'music/detail.html'


class AlbumCreate(CreateView):# when we want to create a new album object
    # what model am I using for the object?
    model = Album
    # what fields do I need in this form for the user to fill out upon creation
    fields = ['artist', 'album_title', 'genre', 'album_logo']

class AlbumUpdate(UpdateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']

class AlbumDelete(DeleteView):
    model = Album
    success_url = reverse_lazy('music:index')
    
class UserFormView(View):
    # what is the form's blueprint/class?
    form_class = UserForm
    template_name = 'music/registration_form.html'

    # whenever the user calls the form it's a get request, go here and display a blank form
    def get(self, request):
        form = self.form_class(None)# no data by default in the blank form
        return render(request, self.template_name, {'form': form})
    
    # process form data
    def post(self, request):
        form = self.form_class(request.POST) # pass in the user's data to that was submitted in form 

        if form.is_valid():
            user = form.save(commit=False) # create an object from the form, but don't save the form's data to the database yet

            # cleaned (normalized) data
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()# now save them to the database

            # returns User onjects if credentials are correct
            user = authenticate(username=username, password=password)

            if user is not None:
                if user.is_active:
                    login(request, user)
                    # request.user.username
                    # now redirect them to a page after login
                    return redirect('music:index')
                    
        # if it doesn't work, have them try again
        return render(request, self.template_name, {'form': form})
        

website/music/templates/music/album_form.html
{% extends 'music/base.html' %}
{% block title %} Add New Album {% endblock %}

{% block body %}

<div class='container-fluid'>

    <div class='row'>
        <div class='col-sm-12 col-md-7'>
            <div class='panel-body'>
                <!-- enctype allows your form to handle what ever data type is passed into it-->
                <form class='form-horizontal' action='' method='post' enctype='multipart/form-data'>
                    {% csrf_token %}
                    {% include 'music/form-template.html' %}<!-- this will be our generic form template-->
                    <div class='form-group'>
                        <div class='col-sm-offset-2 col-sm-10'>
                            <button type='submit' class='btn btn-success'>Submit</button>
                        </div>
                    </div>
                </form>

            </div>
        </div>
    </div>

</div>

{% endblock %}

website/music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load staticfiles %}
    <link rel='stylesheet' type='text/css' href='{% static 'music\style.css' %}' />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Satisfy">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <title>{% block title %}CloudMusic{% endblock %}</title>
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'music:index' %}">CloudMusic</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
        <!-- now add items to the actual nav bar -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link fa fa-th" href="#">&nbsp;Albums</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link fa fa-headphones" href="#">&nbsp;Songs</a>
                </li>
                <!--Drop Down Menu if I want it later -->
                <!--<li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Dropdown
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                -->
        </li>
            <!--   <li class="nav-item">
                    <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                </li>
            --> 
            </ul>
        <form class="form-inline my-2 my-lg-0" method="get">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>

        <ul class="navbar-nav mr-auto navbar-right">
            <li class="nav-item">
                <a class="nav-link fa fa-plus-circle" href="{% url 'music:album-add' %}">&nbsp; Add Album</a>
            </li>
            <li class="nav-item">
                <a class="nav-link fa fa-power-off" href="#">&nbsp; Logout</a>
            </li>
        
        </ul>
    </div>
    </nav>
{% block body %}


{% endblock %}
</body>
</html>

website/music/templates/music/detail.html
{% extends 'music/base.html' %}
{% block title %}Album Details{% endblock %}

{% block body %}

<div class="card text-center" style="width: 100%;">
  <img class="card-img-top" src="{{ album.album_logo.url }}" style='height: 300px;' alt="Album Logo">
  <div class="card-body">
    <h5 class="card-title">{{ album.album_title }}</h5>
  </div>
  <ul class="list-group list-group-flush">
    {% for song in album.song_set.all %}
    {% if song.is_favorite %}
      <li class="list-group-item fa fa-star">{{ song.song_title }}</li>
        {% else %}
          <li class="list-group-item">{{ song.song_title }}</li>
        {% endif %}
        <br>
        {% endfor %}
  </ul>
  <div class="card-body">
    <a href="#" class="card-link fa fa-plus-circle">&nbsp; Add Song</a>
    <form method="post" action="{% url 'music:album-delete' album.id %}">
      {% csrf_token %}
      <button type="submit" class="btn btn-primary fa fa-trash">&nbsp;</button>
    </form>
  </div>
</div>
{% endblock body %}

website/music/templates/music/form-template.html
{% for field in form %}

<div class='form-group'>
    <div class='col-sm-offset-2 col-sm-10'>
        <span class='text-danger small'>{{ field.errors }}</span>
    </div>
    <!-- this is setting the label that goes with the input in the form -->
    <label class='control-label col-sm-2'> {{ field.label_tag }}</label>
    <!-- this is the actual input box -->
    <div class='col-sm-10'> {{ field }}</div>
</div>
{% endfor %}

website/music/templates/music/index.html
{% extends 'music/base.html' %}

{% block body %}
<div class="container-fluid">
    <div class="row">
            {% for album in all_albums %} 
            
                <div class="card col-md-4">
                    <a href="{% url 'music:detail' album.id %}">
                        <img src="{{ album.album_logo.url }}" height="300px", class="card-img-top img-responsive" /><br/>
                    </a>
                    <div class="card-body" >
                        <h5 class="text-muted">{{ album.album_title }}</h6>
                        <div class="btn-group" role="group" aria-label="Basic example">
                            <form method="get" action="{% url 'music:detail' album.id %}">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-primary fa fa-eye" style="border-radius: 7px;">&nbsp;</button>
                                </form>
                                <form method="get" action="{% url 'music:album-update' album.id %}">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-primary fa fa-pencil" style="border-radius: 7px;">&nbsp;</button>
                                </form>
                                <form method="post" action="{% url 'music:album-delete' album.id %}">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-primary fa fa-trash">&nbsp;</button>
                                </form>
                        </div>
                    </div>
                </div>
  
      {% endfor %}
    </div>
</div>

{% endblock body %}

website/music/templates/music/registration_form.html
{% extends 'music/base.html' %}
{% block title %} Register {% endblock %}

{% block body %}

<div class='container-fluid'>

    <div class='row'>
        <div class='col-sm-12 col-md-7'>
            <div class='panel-body'>
            <h3>Create New Account</h3>
                <!-- enctype allows your form to handle what ever data type is passed into it-->
                <form class='form-horizontal' action='' method='post' enctype='multipart/form-data'>
                    {% csrf_token %}
                    {% include 'music/form-template.html' %}<!-- this will be our generic form template-->
                    <div class='form-group'>
                        <div class='col-sm-offset-2 col-sm-10'>
                            <button type='submit' class='btn btn-success'>Submit</button>
                        </div>
                    </div>
                </form>

            </div>
        </div>
    </div>

</div>

{% endblock %}